#!/bin/bash

function hc() {
    herbstclient "$@"
}

Mod=Mod4

if ! hc tag_status | grep "Fun" >/dev/null || [[ $1 = -f ]]  ; then
	TAGS=$(hc tag_status | wc -w)
	hc add "Fun"
	if [[ $TAGS -ge 9 ]] ; then
		echo "$0: too many tags; will not get a keybinding" >&2
	else
		hc keybind "$Mod-$(( TAGS + 1 ))" use "Fun"
		hc keybind "$Mod-Shift-$(( TAGS + 1 ))" move "Fun"
	fi
fi

hc set frame_gap tag=Fun 100
hc set window_gap tag=Fun 100

# layout
#hc load Fun '
#(split horizontal:0.15:1 (clients horizontal:0) (clients grid:4))'


#hc rule instance="something" tag=Fun index=001
#hc rule instance="mutt" tag=Fun index=002
#hc rule instance="irssi" tag=Fun index=003
#hc rule instance="ncmpcpp" tag=Fun index=004
#hc rule instance="wyrd" tag=Fun index=005

# autostart applications

#pgrep newsbeuter >/dev/null || urxvtc -name newsbeuter -e newsbeuter &
#pgrep mutt >/dev/null || urxvtc -name mutt -e mutt &
#pgrep ncmpcpp >/dev/null || urxvtc -name ncmpcpp -e ncmpcpp &
#screen -ls | grep "irssi[[:space:]]*(Attached)" >/dev/null || urxvtc -name irssi -e screen -S irssi -xR irssi &
#pgrep wyrd >/dev/null || urxvtc -name wyrd -e wyrd &




#(split horizontal:0.300000:0 (clients vertical:0 0x4200007) (clients vertical:0 0x3800010))
#;
