#!/bin/bash

function hc() {
    herbstclient "$@"
}

Mod=Mod4

if ! hc tag_status | grep "Internet" >/dev/null || [[ $1 = -f ]]  ; then
	TAGS=$(hc tag_status | wc -w)
	hc add "Internet"
	if [[ $TAGS -ge 9 ]] ; then
		echo "$0: too many tags; will not get a keybinding" >&2
	else
		hc keybind "$Mod-$(( TAGS + 1 ))" use "Internet"
		hc keybind "$Mod-Shift-$(( TAGS + 1 ))" move "Internet"
	fi
fi

# layout
hc load Internet '
(clients vertical:1 0x4000003 0x7600007)


hc rule instance="newsbeuter" tag=Internet index=020
hc rule instance=Internet tag=Internet index=021
hc rule instance="Internet" tag=Internet index=022
hc rule instance="ncmpcpp" tag=Internet index=023
hc rule instance="wyrd" tag=Internet index=024

# autostart applications

pgrep newsbeuter >/dev/null || urxvtc -name newsbeuter -e newsbeuter &
pgrep mutt >/dev/null || urxvtc -name mutt -e mutt &
pgrep ncmpcpp >/dev/null || urxvtc -name ncmpcpp -e ncmpcpp &
screen -ls | grep "irssi[[:space:]]*(Attached)" >/dev/null || urxvtc -name irssi -e screen -S irssi -xR irssi &
pgrep wyrd >/dev/null || urxvtc -name wyrd -e wyrd '
