#!/bin/bash

function hc() {
    herbstclient "$@"
}

Mod=Mod4

if ! hc tag_status | grep "PDF" >/dev/null || [[ $1 = -f ]]  ; then
	TAGS=$(hc tag_status | wc -w)
	hc add "PDF"
	if [[ $TAGS -ge 9 ]] ; then
		echo "$0: too many tags; will not get a keybinding" >&2
	else
		hc keybind "$Mod-$(( TAGS + 1 ))" use "PDF"
		hc keybind "$Mod-Shift-$(( TAGS + 1 ))" move "PDF"
	fi
fi

# layout
hc load PDF '
(split horizontal:0.300000:0 
  (clients vertical:0 0x4200007) 
  (clients vertical:0 0x3800010)
) '


#(split horizontal:0.450000:1
#  (split vertical:0.500000:0
#    (split vertical:0.500000:1
#	  (clients vertical:0 )
#	  (clients vertical:0 ))
#   	(clients horizontal:0 ))
#  (split vertical:0.550000:0
#    (clients vertical:0 )
#   	(clients vertical:0 )))'
# rules
hc rule instance="newsbeuter" tag=PDF index=000
hc rule instance="mutt" tag=PDF index=001
hc rule instance="irssi" tag=PDF index=10
hc rule instance="ncmpcpp" tag=PDF index=01
hc rule instance="wyrd" tag=PDF index=11

# autostart applications

pgrep newsbeuter >/dev/null || urxvtc -name newsbeuter -e newsbeuter &
pgrep mutt >/dev/null || urxvtc -name mutt -e mutt &
pgrep ncmpcpp >/dev/null || urxvtc -name ncmpcpp -e ncmpcpp &
screen -ls | grep "irssi[[:space:]]*(Attached)" >/dev/null || urxvtc -name irssi -e screen -S irssi -xR irssi &
pgrep wyrd >/dev/null || urxvtc -name wyrd -e wyrd &



#hc load PDF '
#(split horizontal:0.300000:0 (clients vertical:0 0x4200007) (clients vertical:0 0x3800010))
#;
