(use-package elpy)
(use-package ess)
(use-package ess-R-data-view)
(use-package ess-smart-underscore)
(use-package ess-view)
(use-package flyspell-correct)
;; (use-package intellij-theme)
;; (use-package lab-themes)
(use-package magic-latex-buffer)
(use-package magit)
(use-package markdown-mode+)
(use-package markdown-toc)
;; (use-package poet-theme)
;; (use-package doom-themes)
(use-package helm-bibtex)
;; (use-package smart-mode-line)
;; (use-package )
;; (use-package )
;; (use-package )
;; (use-package )
;; (use-package )
;; (use-package )
;; (use-package )
;; (use-package )
;; (use-package )
